config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'about', to: 'home#about'
  get 'travel', to: 'home#travel'
  get 'signin', to: 'home#authen'
  
  # get 'home/index'

  resources 'members' do
    resources 'coordinates'
  end
  resources 'committees'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/models/committee.rb
class Committee < ActiveRecord::Base
    belongs_to :ward
    has_many :coordinates
end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
    belongs_to :wards
    belongs_to :committees
end

app/models/project.rb
class Project < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
    validate :must_be_member
    
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            if auth.credentials
                user.oauth_token = auth.credentials.token
                user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            end
            if user.valid?
                user.role = find_role(user.email)
                user.save!
            end
        end
    end
    
    def must_be_member
        errors.add(:base, 'User must be a rishi member') if !UserList.exists?(:email => email)
    end
        
    def self.check_member(user_id)
        if User.exists?(:uid => user_id)
            return true
        else
            return false
        end
    end
    
    def self.find_role(email)
        return UserList.where(:email => email).first.role
    end        
end

app/models/user_list.rb
class UserList < ActiveRecord::Base
end

app/models/ward.rb
class Ward < ActiveRecord::Base
    has_many :committees
    has_many :coordinates
    
    def coordinates_list()
      coords = self.coordinates
      list_of_coords = []
      coords.each do |c|
        list_of_coords << [c.lat, c.lng]
      end
      list_of_coords
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find_by_uid(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  def index
    @projects = Project.all
    @projects.each do |proj|
      puts proj.name
      puts proj.intro_img
    end
  end
  def show
    @project = Project.find(params[:id])
    @name = @project.name
    @text = @project.intro
    @timeline = "Timeline"
  end
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController
    def coordinate_params
        params.require(:coordinate).permit(:lat, :lng)
    end
    
    def return_lat(param)
        param[:latitude]
    end
    
    def return_lng(param)
        param[:longitude]
    end
    
    def return_category(param)
        param[:category]
    end
    
    def return_marker_name(param)
        param[:marker_name]
    end
    
    def create
        input_lat = return_lat(params[:coordinate])
        input_lng = return_lng(params[:coordinate])
        input_category = return_category(params[:category])
        input_marker_name = return_marker_name(params[:marker])
        
        if !Coordinate.exists?(:lat => input_lat.to_f, :lng => input_lng.to_f)
            coord = Coordinate.create(:lat => input_lat.to_f, :lng => input_lng.to_f)
            comm = Committee.create(:name => input_marker_name)
            comm.category = input_category
            comm.coordinates << coord
            comm.save!
        else
            flash[:notice] = "Marker already exists at this coordinate"
        end
        redirect_to members_path
        
        # if Coordinate.exists?(:lat => input_lat, :lng => input_lng)
        #     flash[:notice] = 'Marker already exists at this coordinate'
        #     redirect_to members_path
        # else
        #     if Ward.exists?(:name => input_ward_name)
        #         ward = Ward.find_by_name(input_ward_name)
        #     else
        #         ward = Ward.create(:name => input_ward_name)
        #     end
        #     coord = Coordinate.create(:lat => input_lat, :lng => input_lng)
        #     if Committee.exists?(:name => input_marker_name) 
        #         comm = Committee.find_by_name(input_marker_name)
        #     else
        #         comm = Committee.create(:name => input_marker_name)
        #     end
        #     comm.ward = ward
        #     comm.coordinates << coord
        #     comm.save!
        #     redirect_to members_path
    end
    
    def destroy 
        id = params[:id]
        coord = Coordinate.find_by_id(id)
        coord.destroy!
        redirect_to members_path
    end
    
    def edit
        @coordinate = Coordinate.find(params[:id])
        @member = User.find(params[:member_id])
    end
    
    def update
        @coordinate = Coordinate.find(params[:id])
        @coordinate.update_attributes!(coordinate_params)
        flash[:notice] = "Marker was successfully updated."
        redirect_to members_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api_key = ENV['google_api_key']
    regions = []
    Ward.all.each do |ward|
      regions << ward.coordinates_list()
    end
    gon.regions = regions
    
    markers = []
    
    Committee.all.each do |c|
      if c.coordinates.size != 0
        l = [c.name, c.category, c.coordinates.last.lat, c.coordinates.last.lng]
        markers << l
      end
    end
    gon.markers = markers
   
  end
  
  
  def about
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    # Passes in @member to form_tag in /members.
    before_action :check_login

    def check_login
        if session[:user_id] == nil
            flash[:notice] = "Please log in to access this page."
            redirect_to root_path, error: 'Please log in to access this page.'
            return
        elsif !User.check_member(session[:user_id])
            flash[:notice] = "Please request to be added as a Rishi member"
            redirect_to root_path, error: 'Please request to be added as a Rishi member'
            return
        end
    end
     
    def index
        user_id = session[:user_id]
        @member = User.find_by_uid(user_id)
        @committees = Committee.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_provider_and_uid(auth_hash.provider,auth_hash.uid) || User.from_omniauth(auth_hash)

    session[:user_id]=@user.uid
    redirect_to '/members'
  end

  def destroy
      session.delete(:user_id)
      current_user=nil
      flash[:notice]='Logged out successfully'
      redirect_to root_path
  end
  
  protected

  def auth_hash
    request.env['omniauth.auth']
  end
  
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/committees/_popup_partial.html.erb
<%= link_to 'Water', "/committees" %>

app/views/committees/index.html.erb
<% @projects.each do |proj| %>
    <div class=cmt>
        <div class="picture"><img src=<%= image_path(proj.intro_img) %>></img></div>
        <div class="cmt_name"><%= link_to proj.name, committee_path(proj) %></div>
        <hr>
        <div class="introduction">
            <p><%= proj.intro %></p>
        </div>
    </div>
<% end %>

app/views/committees/popup_partial.html.erb
<%= link_to 'Water', "/committees" %>

app/views/committees/show.html.erb
<div class="cmt_name"><%= @name %></div>
    <hr>
    <div class="introduction">
        <p><%= @text %></p>
    </div>
</div>

<% if !current_user.nil? %>
    <% if current_user.role.eql? "internal" or current_user.role.eql? "executive" %>
        <%= puts "my id: "+current_user.uid %>
        <div class="cmt_name"><%= @timeline %></div>
        <hr>
    <% end %>
    <% if current_user.role.eql? "executive" %>
        <%= puts "my id: "+current_user.uid %>
        <%= link_to "Edit Committees", '' %>
    <% end %>
<% end %>

app/views/coordinates/edit.html.haml
%h1 Edit Existing Marker

= form_tag member_coordinate_path(:member_id => @member.id, :id => @coordinate.id), :method => :put do

  = label :coordinate, :lat, 'Latitude'
  = text_field :coordinate, 'lat'
  
  = label :coordinate, :lng, 'Longitude'
  = text_field :coordinate, 'lng'

  = submit_tag 'Update Marker Coordinate', :id => 'update_marker'

app/views/home/about.html.erb
<h1>About</h1>

<div>
                <h3 style="color:#ffffff">Our Mission</h3>
                <br>
                <p style="color:#ffffff"><strong>Our mission is to promote the sustainable development of rural Indian communities. <br>In partnership with local community members and social enterprises, we identify issues central to our target communities and provide the resource to implement solutions through extensive field research and on-campus initiatives.</strong></p>
                <br>
                <h3 style="color:#ffffff">About Us</h3>
                <br>
                <p style="color:#ffffff">We are a diverse group of passtionate and energetic individuals moving forward the dialogue on equity and resilience through our projects. We operate on a university model where undergraduate chapters partner with villages in need and a single National team serves to empower these chapters with the resources and guidance. Finally, our donors who believe in our mission allow us to make our projects a reality.</p>
                <br>
                <br>
            </div>

app/views/home/authen.html.erb
<div id="authen_div">
<h1>Sign in with Google</h1>

<body id="internal">RISHI would like to get permission to your Google account.</body>
<body id="internal">Currently, accounts are only supported for internal club members.</body>
<body id="internal">Please contact an executive member to get permission to access the internal site.</body>


<form>
  <input class="auth" id="authen" type="button" value="Authorize" onclick="window.location.href='/auth/google_oauth2'" />
  <input class="auth" id="authenc" type="button" value="Cancel" onclick="window.location.href='/'" />
</form>
</div>

app/views/home/index.html.erb
<%= include_gon %>
<div class="top">
    <table>
        <tr>
            <td>
                <h3>Water</h3>
                <div class = "check">
                    <input type="checkbox" id="waterCheckbox" onclick="toggleGroup('water')" CHECKED />
                    <label for = "waterCheckbox"></label>
                    <br/>
                </div>
            </td>
            <td>
                <h3>Empowerment</h3>
                <div class = "check">
                    <input type="checkbox" id="empowermentCheckbox" onclick="toggleGroup('empowerment')" CHECKED/>
                    <label for = "empowermentCheckbox"></label>
                    <br/>
                </div>
            </td>
            <td>
                <h3>Health</h3>
                <div class = "check">
                    <input type="checkbox" id="healthCheckbox" onclick="toggleGroup('health')" CHECKED/>
                    <label for = "healthCheckbox"></label>
                    <br/>
                </div>
            </td>
            <td>
                <h3>Education</h3>
                <div class = "check">
                    <input type="checkbox" id="educationCheckbox" onclick="toggleGroup('education')" CHECKED/>
                    <label for = "educationCheckbox"></label>
                    <br/>
                </div>
            </td>
            <td>
                <h3>Agriculture</h3>
                <div class = "check">
                    <input type="checkbox" id="agricultureCheckbox" onclick="toggleGroup('agriculture')" CHECKED/>
                    <label for = "agricultureCheckbox"></label>
                    <br/>
                </div>
            </td>
            <td>
                <h3>POI</h3>
                <div class = "check">
                    <input type="checkbox" id="poiCheckbox" onclick="toggleGroup('poi')" CHECKED/>
                    <label for = "poiCheckbox"></label>
                </div>
            </td>
        </tr>
    </table>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=@api_key%>&callback=initMap"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<div id="map" style='width: 100%; height: 800px; margin:auto;'></div>

<script type="text/javascript">

var markerGroups = {
    "water": [],
    "health": [],
    "education": [],
    "empowerment": [],
    "agriculture": [],
    "poi": []
    
};

var customIcons = {
    education: {
        icon: '/assets/education_small.png'
    },
    health: {
        icon: '/assets/health_small.png'
    },
    agriculture: {
        icon: '/assets/agriculture.png'
    },
    
    water: {
        icon: '/assets/logo_small.png'
    },
    empowerment: {
        icon: '/assets/logo_small.png'
    },
    poi: {
        icon: '/assets/logo_small.png'
    }

};

 
function load() {
    map = new google.maps.Map(document.getElementById("map"), {
        center: new google.maps.LatLng(30.560554149332777, 77.52290278673172),
        zoom: 14
    });
    map.setOptions({ minZoom: 14, maxZoom: 16 });
    
    var regionCoords = [[]];
    var polygons = []
    colors = ['red', 'blue', 'green', 'orange', 'brown']
    for (i = 0; i < gon.regions.length; i++) {
        regionCoords[i] = []
        for (var j = 0; j < gon.regions[i].length; j++) {
            regionCoords[i].push({
                lat: gon.regions[i][j][0],
                lng: gon.regions[i][j][1]
            });
        }
        polygons.push(new google.maps.Polygon({
            paths: regionCoords[i],
            strokeColor: colors[i],
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: colors[i],
            fillOpacity: 0.35
        }));
        polygons[polygons.length-1].setMap(map);
    }

    var infoWindow = new google.maps.InfoWindow();
    var markers = gon.markers;
    console.log(markers)
    var bounds = new google.maps.LatLngBounds();
    for (var i = 0; i < markers.length; i++) {
        var name = markers[i][0];
        console.log(name);
        var address = "";
        var point = new google.maps.LatLng(
        parseFloat(markers[i][2]),
        parseFloat(markers[i][3]));
        bounds.extend(point);
        var type = markers[i][1];
        var html = "<b style='color:black'>" + name + "</b> <br/>" + address;
        var icon = customIcons[type] || {};
        var marker = new google.maps.Marker({
            map: map,
            position: point,
            icon: icon.icon
        });
        if (type in markerGroups) {
            markerGroups[type].push(marker);
        } else {
            markerGroups[type] = []
            markerGroups[type].push(marker);
        }
        bindInfoWindow(marker, map, infoWindow, html);
    }
}

function bindInfoWindow(marker, map, infoWindow, html) {
    google.maps.event.addListener(marker, 'click', function () {
        infoWindow.setContent(html);
        infoWindow.open(map, marker);
    });
}

function downloadUrl(url, callback) {
    var request = window.ActiveXObject ? new ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpRequest;
    request.onreadystatechange = function () {
        if (request.readyState == 4) {
            request.onreadystatechange = doNothing;
            callback(request, request.status);
        }
    };
    request.open('GET', url, true);
    request.send(null);
}

function toggleGroup(type) {
    for (var i = 0; i < markerGroups[type].length; i++) {
        // alert(markerGroups[type][i]);
        var marker = markerGroups[type][i];
        if (!marker.getVisible()) {
            marker.setVisible(true);
        } else {
            marker.setVisible(false);
        }
    }
}
google.maps.event.addDomListener(window, 'load', load);

function parseXml(str) {
    if (window.ActiveXObject) {
        var doc = new ActiveXObject('MicrosoftXMLDOM');
        doc.loadXML(str);
        return doc;
    } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
    }
}

var xmlStr = '<markers><marker name="water1" address="" lat="30.560554149332777" lng="77.52290278673172" type="water"/><marker name="women1" address="" lat="30.57" lng="77.524" type="women"/></markers>';


</script>

app/views/home/travel.html.erb
<div class='travelpane'>
    <div class='panetitle'>Travel</div>
    <div class='bigpic'>
	    <img src='/assets/travel.png'>
    </div>

    <div class='contentHolder'>
        <p class='introduction'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor pulvinar felis sit amet pretium. Proin lobortis, nisi in lacinia porttitor, velit felis tempor magna, et imperdiet lacus sapien eget justo. Sed at varius elit. Donec eu arcu a lorem cursus pretium. Nunc gravida enim et massa condimentum maximus. In sapien nunc, lacinia eget orci vitae, condimentum rutrum ex. Duis id ex dignissim, tempus nisl at, posuere turpis. Pellentesque tempor, turpis ac sagittis ornare, erat lorem eleifend ante, vitae blandit massa nulla ac nibh. Suspendisse nec luctus felis. Vestibulum dignissim dolor ut lacus volutpat lacinia. Maecenas vestibulum leo ex, eu consequat lectus efficitur et.</p>
        <p>Curabitur tincidunt maximus velit, sit amet maximus est accumsan sed. Etiam nec ante a dolor fermentum auctor ut eu justo. Maecenas convallis ornare metus eu consectetur. Sed maximus orci ut ligula convallis, id ornare orci volutpat. Nam semper, elit ac varius venenatis, lacus lacus elementum velit, vitae consequat leo mauris a urna. Cras ut ex commodo, pharetra massa vel, tristique diam. Mauris sed nisi ut turpis vulputate interdum. Suspendisse orci eros, vehicula id dignissim id, elementum malesuada augue. Pellentesque consequat quis nisl ornare malesuada. Etiam ac urna ut mauris tempus volutpat et ut odio. Integer porta, sapien sed pretium bibendum, nunc erat blandit turpis, vel rhoncus dui eros et enim.</p>
        <p>Praesent sapien risus, tempus quis sollicitudin eu, tempus non augue. Sed diam neque, vehicula eu finibus ac, tempor eu ante. Quisque semper urna sit amet lacus sagittis gravida. Nam tincidunt sollicitudin porttitor. Donec malesuada tortor ac massa scelerisque, sed porttitor lectus venenatis. Mauris fermentum tellus vitae mi vulputate, eu mollis turpis auctor. Aliquam suscipit semper libero, a porttitor ex ornare ac. Mauris felis nibh, laoreet at diam mollis, viverra aliquam enim. Donec vehicula tempor fringilla.</p>
    </div>
</div>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Rishi
		= stylesheet_link_tag    'application', media: 'all'
		= javascript_include_tag 'application'
		= csrf_meta_tags
	%body
		- if flash[:notice]
			.alert
				%span.closebtn{:onclick => "this.parentElement.style.display='none';"} ×
				#{flash[:notice]}
		#header.header
			%ul
				- if current_user
					%li
						= link_to "EDIT MAP", members_path
					%li
						= link_to "SIGN OUT", signout_path, method: :delete
				- else
					%li= link_to "SIGN IN", "/signin"
				%li
					%a#donateNav{:href => "http://www.projectrishi.org/donate", :target => "_blank"} DONATE
				%li
					%a#aboutNav{:href => "/about"}ABOUT
				%li
					%a#travelNav{:href => "/travel"} TRAVEL
				%li
					%a#projectsNav{:href => "/committees"} PROJECTS
				%a{:href => "/"}
					.logo>
						%img{:src => "/assets/logo_with_title.png"}/
		= yield

app/views/layouts/authorize.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rishi</title>
  <%= stylesheet_link_tag    'authorize', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'authorize', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

app/views/members/index.html.haml
%h1 Marker Editing

= form_tag member_coordinates_path(:member_id => @member.id) do

  = label :coordinate, :lat, 'Latitude'
  = text_field :coordinate, 'latitude'
  
  = label :coordinate, :lng, 'Longitude'
  = text_field :coordinate, 'longitude'

  = label :category, :category, 'Category'
  = text_field :category, 'category'

  = label :marker, :name, 'Marker Name'
  = text_field :marker, 'marker_name'

  = submit_tag 'Add Marker', :id => "markers_submit"
  
%table#markers
  %thead
    %tr
      %th Category
      %th Name
      %th Latitude
      %th Longitude
      %th Delete
      %th Edit
  %tbody
    - @committees.each do |comm|
      - comm.coordinates.each do |coord|
        %tr
          %td= comm.category
          %td= comm.name
          %td= coord.lat
          %td= coord.lng
          %td= button_to 'Delete', member_coordinate_path(:member_id => @member.id, :id => coord.id), :method => :delete, :confirm => 'Are you sure?', :id => 'delete_marker'
          %td= link_to 'Edit', edit_member_coordinate_path(:member_id => @member.id, :id => coord.id), :id => 'edit_marker'
= link_to 'Back to home page', root_path